# Generated by Django 5.1.3 on 2024-12-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reserva_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente_temporal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
