# Generated by Django 5.1.3 on 2024-12-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reserva_cliente_temporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='menu_item',
        ),
    ]
