# Generated by Django 5.1.3 on 2024-12-03 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_reserva_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente_temporal',
        ),
        migrations.AddField(
            model_name='reserva',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.menuitem'),
        ),
    ]
