# Generated by Django 5.1.3 on 2024-12-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_compra_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
