# Generated by Django 5.1.3 on 2024-12-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_platillo_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('en_preparacion', 'En Preparación'), ('terminado', 'Terminado')], default='en_preparacion', max_length=20),
        ),
    ]
