# Generated by Django 5.1.3 on 2024-12-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_compra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('en_preparacion', 'En Preparación'), ('terminado', 'Terminado'), ('compra_cancelada', 'Compra Cancelada')], default='en_preparacion', max_length=20),
        ),
    ]
